from TauAnalysis.Configuration.tools.tauAnalysisMaker import *

options = Options(
  name='bbAHtoElecTau',
  object_order=['vertex','electron','tau','jet','elecTauPair'],
  plots=[
    Plot('DiTauCandidateQuantities/Mt1MET'),
    Plot('DiTauCandidateQuantities/Mt2MET'),
    Plot('DiTauCandidateQuantities/Mt12MET'),
    Plot('DiTauCandidateQuantities/CDFmethodMass'),
    Plot('DiTauCandidateQuantities/CollinearApproxMass'),
    Plot('DiTauCandidateQuantities/VisMass'),
    Plot('ElectronQuantities/ElectronEta'),
    Plot('ElectronQuantities/ElectronPt'),
    Plot('ElectronQuantities/ElectronPhi'),
    Plot('TauQuantities/TauEta'),
    Plot('TauQuantities/TauPt'),
    Plot('TauQuantities/TauPhi'),
  ]
)

cuts = [
   GenPhaseSpaceCut(),
   TriggerCut(triggerPaths=cms.vstring('HLT_IsoEle15_L1I')),
   VertexCut(cppclass='PATSingleVertexSelector',mode=cms.string('firstVertex'), vertices=cms.InputTag('$last(vertex)'),filter=cms.bool(False),title='Primary Vertex'),
   VertexCut(cppclass='VertexSelector',cut=cms.string('isValid & (chi2prob(chi2,ndof) > 0.01) & (tracksSize >= 2)'),filter=cms.bool(False),plots=[Plot('VertexQuantities/VertexZ')]),
   VertexCut(cppclass='VertexSelector',cut=cms.string('z > -25 & z < +25'),filter=cms.bool(False),plots=[Plot('VertexQuantities/VertexZ')]),
   ElectronCut(cut=cms.string('pt > 15')),
   ElectronCut(cut=cms.string('abs(eta) < 2.1')),
   ElectronCut(cut=cms.string('abs(superCluster.eta) < 1.442 | abs(superCluster.eta) > 1.560')),
   ElectronCut(cut=cms.string('(abs(superCluster.eta) < 1.479 & eSuperClusterOverP < 1.05 & eSuperClusterOverP > 0.95) | (abs(superCluster.eta) > 1.479 & eSuperClusterOverP < 1.12 & eSuperClusterOverP > 0.95)')),
   ElectronCut(cut=cms.string('electronID("robust")>0')),
   ElectronCut(cut=cms.string('trackIso < 1.')),
   ElectronCut(cut=cms.string('(abs(superCluster.eta) < 1.479 & ecalIso < 1.0) | (abs(superCluster.eta) > 1.479 & ecalIso < 2.5)')),
   ElectronCut(cut=cms.string('gsfTrack.isNonnull')),
   ElectronCut(cppclass='PATElectronIpSelector',vertexSource=cms.InputTag('$last(vertex)'),IpMax=cms.double(0.05),filter=cms.bool(False),title='Electron IP'),
   TauCut(cppclass='PATTauAntiOverlapSelector',srcNotToBeFiltered=cms.VInputTag('$last(electron)'),dRmin=cms.double(0.3),filter=cms.bool(False),title='Tau Anti-overlap'),
   TauCut(cut=cms.string('abs(eta) < 2.1')),
   TauCut(cut=cms.string('pt > 20')),
   TauCut(cut=cms.string('(abs(eta)>0.018) & (abs(eta)<0.423 | abs(eta)>0.461) & (abs(eta)<0.770 | abs(eta)>0.806) & (abs(eta)<1.127 | abs(eta)>1.163) & (abs(eta)<1.460 | abs(eta)>1.558)')),
   TauCut(cut=cms.string('tauID("leadingTrackFinding")>0.5')),
   TauCut(cut=cms.string('tauID("leadingTrackPtCut")>0.5')),
   TauCut(cut=cms.string('tauID("trackIsolation")>0.5')),
   TauCut(cut=cms.string('tauID("ecalIsolation")>0.5')),
   TauCut(cut=cms.string('signalTracks.size() = 1 | signalTracks.size() = 3')),
   TauCut(cut=cms.string('tauID("againstElectron") > 0.5')),
   ElecTauPairCut(cut=cms.string('dR12 > 0.7')),
   ElecTauPairCut(cut=cms.string('charge = 0')),
   JetCut(cppclass='PATJetAntiOverlapSelector',srcNotToBeFiltered=cms.VInputTag('$last(electron)','$last(tau)','$last(muon)'),dRmin=cms.double(0.7),filter=cms.bool(False),title='Jet Anti-overlap'),
   JetCut(cut=cms.string('abs(eta) < 2.1')),
   JetCut(cut=cms.string('et > 20')),
   JetCut(cut=cms.string('bDiscriminator("simpleSecondaryVertexBJetTags")>2 | bDiscriminator("combinedSecondaryVertexBJetTags")>0.4')),
   JetCut(cut=cms.string('bDiscriminator("trackCountingHighEffBJetTags")>2.5')),
   ElecTauPairCut(cut=cms.string('mt1MET < 60'))
]